### PR TITLE
[MIG] 14.0 base_user_role_profile

### PR DESCRIPTION
**Pull request by PierrickBrun**

### CODE REVIEW

**Comment by kevinkhao** [comment]
rebased to 14.0
depends on https://github.com/OCA/server-backend/pull/108
fixed multicompany functionality (removed everything related to it)

**Comment by kevinkhao** [comment]
ping @sebastienbeau

**Comment by revskill10** [comment]
When will this merged ?

**Comment by PierrickBrun** [comment]
> When will this merged ?

I removed the draft status as problematic multi-company support has been dropped. It should be ready for reviews now

**Comment by revskill10** [comment]
So if you removed multicommpany feature, is this module usable in a multicompany setup ?

**Comment by PierrickBrun** [comment]
> So if you removed multicommpany feature, is this module usable in a multicompany setup ?

Yes, you will have the same profile in every company you are in. That means if you want to have different profile depending on the company, you will need to have several user accounts.

**Review by dreispt — APPROVED** [review]

**Pull request merged**
