### PR TITLE
[MIG] 14.0 base_external_dbsource

### PR DESCRIPTION
**Pull request by Bilbonet**
stanadar migration

### CODE REVIEW

**Comment by dreispt** [comment]
Precommit and Travis need fixing, please.

**Comment by Bilbonet** [comment]
sorry, I can't fix the problem with travis.
I've tried to fix it, but I didn't achieve to understand the problem with mock.

`2021-10-05 18:02:11,551 5979 ERROR openerp_test odoo.addons.base_external_dbsource.tests.test_base_external_dbsource: ERROR: TestBaseExternalDbsource.test_conn_open
Traceback (most recent call last):
File "/home/travis/build/OCA/server-backend/setup/base_external_dbsource/odoo/addons/base_external_dbsource/tests/test_base_external_dbsource.py", line 248, in test_conn_open
self.dbsource, "connection_open", autospec=True
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mock/mock.py", line 1532, in __enter__
setattr(self.target, self.attribute, new_attr)
AttributeError: 'base.external.dbsource' object attribute 'connection_open' is read-only`

If someone can help with a clue or if wants to continue the migration with another PR.

Thanks.

**Comment by pedrobaeza** [comment]
If this is resumed, c031fde4d5b852bf13d41454ac42af47ec064333 needs to be cherry-picked here.

**Review by enriquemartin — APPROVED** [review]

**Comment by Bilbonet** [comment]
@dreispt is green 🥦🥦🥦

**Comment by etobella** [comment]
Can you fix the commit history? no merge commits should be here, also, a commit named little change or [FIX] are not fit.

**Pull request merged**
