### PR TITLE
11.0[IMP]base_user_role: Added new tab for internal notes in role view

### PR DESCRIPTION
**Pull request by HaraldPanten**
Hi all,

With this new tab, it's possible to describe each role in order to let other users know all details.

### CODE REVIEW

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza , @jbeficent 

Could you take a look at this? It's quite simple, but adds an interesting and useful functionality.

I don't understand why runbot is not running properly.

THX in advance!

**Comment by pedrobaeza** [comment]
Runbot if flickering a lot lately, but it's not your fault. I have forced a rebuild to see.

About the PR, I'm not using this module, so I can't say too much, but starting with, you have changed the permissions for all the files, which you shouldn't do.

**Comment by HaraldPanten** [comment]
I changed the permissions. Runbot is still dying :(

**Comment by HaraldPanten** [comment]
@ValentinVinagre @xavierjimenez

**Review by xavierjimenez — APPROVED** [review]
Code review looks good to me 👍

**Review by ValentinVinagre — APPROVED** [review]
code LGTM

**Comment by pedrobaeza** [comment]
There's an incorrect rebase on this PR with a lot of unrelated changes.

**Pull request closed without merging**
