### PR TITLE
[16.0][MIG] base_user_role: Migrate to version 16.0

### PR DESCRIPTION
**Pull request by apineux**
#184

### CODE REVIEW

**Comment by jcdrubay** [comment]
ducdd@komit-consulting.com and duc.dd@komit-consulting.com are the same user who is not using that email address anymore.
The Github login is: https://github.com/novawish
Let me know if I could help in any way.

**Review by PierrickBrun — APPROVED** [review]
Code review + tests

**Review by sebalix — APPROVED** [review]

**Comment by sebalix** [comment]
LG, merging, thanks!
/ocabot merge nobump

**Pull request merged**
