### PR TITLE
11.0[MIG] base_external_dbsource_mssql

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase now that the dependency has been merged.

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Comment by cubells** [comment]
You must rebase when `base_external_dbsource_sqlite` dependency was merged.

**Review by sebalix — APPROVED** [review]

**Comment by sergio-teruel** [comment]
@pedrobaeza  This PR is ready to merge

**Pull request merged**
