### PR TITLE
[11.0][WIP] [MIG] base_import_match

### PR DESCRIPTION
**Pull request by misern2**
Standard Migration

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by misern2** [comment]
@pedrobaeza test already passed.

Runbot is red and I can't see the full logs.  Is runbot running Ok ?

**Comment by pedrobaeza** [comment]
No, we are having issues with runbot unrelated to the PR. We are trying to find the root cause.

**Comment by pedrobaeza** [comment]
I have restarted to see if we have luck with runbot.

**Review by HaraldPanten — APPROVED** [review]
Functional review.

👍

**Comment by pedrobaeza** [comment]
Please squash your migration commits

**Comment by harlibeub** [comment]
10 month last activity... isnt this pr ok?

**Comment by pedrobaeza** [comment]
@harlibeub instead of complying, review the PR for getting this merged: https://odoo-community.org/page/review

**Comment by harlibeub** [comment]
if i follow the rev. guide on https://odoo-community.org/page/review i should be able to start a runbot.. correct?

on https://runbot.odoo-community.org/runbot/build/3384192 i forced the rebuild, but if i login there.. base_import_match module not available..

something i do wrong?
is it out of date?

t.y.

**Comment by harlibeub** [comment]
whats up? not merge then we loose good module for future...

why duration to merge so long? why nobody handle?

**Review by dreispt — APPROVED** [review]

**Pull request merged**
