### PR TITLE
[MIG][12.0] base_external_dbsource_sqlite: Migration to v12.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT21045
@carlosdauden @chienandalu Can you review?

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Where's the migration commit? :sweat_smile:

**Comment by sergio-teruel** [comment]
@chienandalu Uuuppps!!

**Comment by sergio-teruel** [comment]
@carlosdauden @chienandalu ready for review... I know that coverage is low....

**Review by chienandalu — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
