### PR TITLE
[MIG] base_user_role_company: Migration to 15.0

### PR DESCRIPTION
**Pull request by Tatider**
Depends on [base_user_role](https://github.com/OCA/server-backend/pull/138) migration.

### CODE REVIEW

**Comment by Tatider** [comment]
Can't be build until [base_user_role](https://github.com/OCA/server-backend/pull/138) is merged.

**Comment by ivantodorovich** [comment]
https://github.com/OCA/server-backend/pull/138 is merged, could you rebase?

**Comment by dreispt** [comment]
Note that there are two important fixes for this feature, #147 and #149

**Pull request closed without merging**
