### PR TITLE
[14.0][MIG] base_global_discount

### PR DESCRIPTION
**Pull request by omar7r**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@omar7r Could you check Travis as 14.0 branch seems to be green without this?

**Comment by omar7r** [comment]
Hi @rousseldenis the error in travis is raised from base_user_role module, not this.

**Comment by rousseldenis** [comment]
> Hi @rousseldenis the error in travis is raised from base_user_role module, not this.

@omar7r Could you rebase as 14.0 branch seems to be green ?

**Review by remi-filament — APPROVED** [review]
Functional tests with sale OK.
Thanks for this migration, only missing rebase to cet Travis green !

**Comment by omar7r** [comment]
@rousseldenis The last commit of origin's branch is earlier than this PR, anything to rebase.

**Comment by francesco-ooops** [comment]
@omar7r any plan to finish/merge this one?
Thanks!

**Comment by omar7r** [comment]
Rebased but, the error in travis is raised from base_user_role module, not this.

**Comment by manuelcalerosolis** [comment]
Functional tests OK!

 @omar7r just one thing, there are terms that have not been translated into Spanish and for users in our country it is uncomfortable, could you include these translations?

Manage Global Discounts -> Gestionar Descuentos Globales 
Purchase Global Discounts (readonly) -> Compra Descuentos Globales (solo lectura)
Sale Global Discounts (readonly) -> Venta Descuentos Globales (solo lectura)

Thanks

**Review by manuelcalerosolis — APPROVED** [review]

**Comment by elvise** [comment]
Hi! Any plan for complete and merge this one ?
Thanks !
@omar7r

**Comment by iwkse** [comment]
Hi, it's required to fix tests for base_user_role to merge it or can be merged?
Thank you 
@manuelcalerosolis
@remi-filament

**Comment by iwkse** [comment]
Any news about merging this PR?

@rafaelbn @chienandalu @pedrobaeza

**Comment by pedrobaeza** [comment]
Let's try, but Travis is right now red:

/ocabot migration base_global_discount

/ocabot merge nobump

**Comment by iwkse** [comment]
> @pedrobaeza your merge command was aborted due to failed check(s), which you can inspect on [this commit of 14.0-ocabot-merge-pr-131-by-pedrobaeza-bump-nobump](https://github.com/OCA/server-backend/commits/35a8a3b8ddcc8b113f546b312c1a704ecfe956fe).
> 
> After fixing the problem, you can re-issue a merge command. Please refrain from merging manually as it will most probably make the target branch red.

Yes, it fails on base_user_role, which is a module already ported to 14.0. If it was merged it means it wasn't such test issue. I will have to investigate

**Comment by iwkse** [comment]
@omar7r please can you rebase or let's #145 being merged.

**Pull request merged**
