### PR TITLE
[IMP] base_user_role: Adding a new tab for user comments in roles form.

### PR DESCRIPTION
**Pull request by HaraldPanten**
With this new tab, it's possible to describe each role in order to let other users know all details.

### CODE REVIEW

**Comment by sebalix** [comment]
Hi @HaraldPanten 
It's not the same commit than https://github.com/OCA/server-backend/pull/39/commits, but I suppose it doesn't matter... ? @pedrobaeza what do you think? Should it be a real cherry-pick from `11.0` branch?

**Comment by pedrobaeza** [comment]
In this case, it doesn't matter, as the author is the same.

**Review by sebalix — APPROVED** [review]
Then :+1:

**Review by ValentinVinagre — APPROVED** [review]
👍 LGTM

**Comment by HaraldPanten** [comment]
@pedrobaeza Do you that this PR can be merged?

THX!

**Pull request merged**
