### PR TITLE
[IMP] base_global_discount: Add discounted amount selection

### PR DESCRIPTION
**Pull request by SirTakobi**
Allow to apply global discounts on total

~~Runboat should be fixed after https://github.com/OCA/server-backend/pull/164~~

### CODE REVIEW

**Review by eLBati — APPROVED** [review]
Tested

**Comment by SirTakobi** [comment]
@OCA/server-environment-maintainers can someone have a look?
Not very sure this is the correct team, please let me know if I have to mention something else, thanks!

**Comment by SirTakobi** [comment]
@OCA/tools-maintainers can someone have a look? Thanks!

**Comment by simahawk** [comment]
I'd ping an author instead (just look at the history). @chienandalu ping? :)

**Comment by pedrobaeza** [comment]
Sorry, we are not using 12.0 anymore. Anyways, this is useless without the implementation in `account_global_discount`.

**Comment by SirTakobi** [comment]
> Sorry, we are not using 12.0 anymore. Anyways, this is useless without the implementation in `account_global_discount`.

Thanks for the feedback!
This base module is already pretty much useless without the implementations in depending modules, it is mentioned in the README too:
> It doesn't do much for itself, so account_global_discount or purchase_global_discount should be installed to benefit from it.

(ref. https://github.com/OCA/server-backend/blob/3cd63d8a9b42ff4bcaca2c015737a7181b2da1e3/base_global_discount/README.rst#base-global-discount)
I just implemented this change here so I don't have to duplicate (N-plicate) the same code in N depending modules; right now this is only used in https://github.com/OCA/account-invoicing/pull/1150 but I suppose it might be used in `purchase_global_discount` (that I can't find right now) too.

**Comment by pedrobaeza** [comment]
OK, but as stated, we don't work anymore with 12.0 at Tecnativa.

**Comment by SirTakobi** [comment]
@OCA/tools-maintainers can someone have a look? Thanks!

**Review by chienandalu — APPROVED** [review]
Ok for me :+1:

**Pull request merged**
