### PR TITLE
[12.0][IMP] base_global_discount: add fixed discount selection

### PR DESCRIPTION
**Pull request by primes2h**
It adds fixed discount as global discount type.

See https://github.com/OCA/server-backend/pull/267 for v. 14.0.

### CODE REVIEW

**Review by matteoopenf — APPROVED** [review]

**Comment by ygol** [comment]
hello,
Is it within this scope to add global discount amount either based on tax included/excluded base?
Example with fix discount based on included TAX:
2046.45 before tax
-900 discount
112.55 TAX
2159 Tax included
-900
1259 after discount
 Thank you

**Comment by primes2h** [comment]
> hello, Is it within this scope to add global discount amount either based on tax included/excluded base? Example with fix discount based on included TAX: 2046.45 before tax -900 discount 112.55 TAX 2159 Tax included -900 1259 after discount Thank you

Hello, fixed discounts don't work with subtotal when you have more than one invoice line. [*]
When invoice lines are >= 2 you don't know how to proportionally distribute discount on the lines.

[*] with one line, fixed discount is covered by https://github.com/OCA/account-invoicing/tree/12.0/account_invoice_fixed_discount

**Comment by primes2h** [comment]
> [*] with one line, fixed discount is covered by https://github.com/OCA/account-invoicing/tree/12.0/account_invoice_fixed_discount

I mean, with one or more lines.

**Comment by ygol** [comment]
> > [*] with one line, fixed discount is covered by https://github.com/OCA/account-invoicing/tree/12.0/account_invoice_fixed_discount
> 
> I mean, with one or more lines.

Thank you @primes2h

**Comment by primes2h** [comment]
> > > [*] with one line, fixed discount is covered by https://github.com/OCA/account-invoicing/tree/12.0/account_invoice_fixed_discount
> > 
> > 
> > I mean, with one or more lines.
> 
> Thank you @primes2h

You're welcome!
Feel free to do a review if you want. ;-)

**Pull request closed without merging**
