### PR TITLE
11.0 mig base external dbsource mysql

### PR DESCRIPTION
**Pull request by max3903**
Superseeds #7 (merged by mistake)

### CODE REVIEW

**Comment by max3903** [comment]
@pedrobaeza Correct me if I am wrong but I think:

- we should get `libmysqlclient-dev` installed in the runbot docker instance
- the module should list `mysqlclient` as the Python dependency, not `MySQLdb`

**Comment by max3903** [comment]
https://github.com/Tecnativa/server-backend/pull/1

**Comment by max3903** [comment]
@sergio-teruel I just sent an email to support - at - odoo-community.org to get libmysqlclient-dev installed on Runbot.

:+1:

**Comment by moylop260** [comment]
You can add `libmysqlclient-dev` to `.travis.yml` in the section of packages

**Comment by max3903** [comment]
https://github.com/Tecnativa/server-backend/pull/2

**Comment by max3903** [comment]
@sergio-teruel Rebased on OCA/11.0 in https://github.com/Tecnativa/server-backend/pull/3

**Comment by max3903** [comment]
:+1:

**Pull request merged**
