### PR TITLE
[13.][MIG] base_import_match

### PR DESCRIPTION
**Pull request by Rad0van**
Fairly standard migration. Had to put fields into frozenset to prevent WARNING in tools/cache.py ormcache.lookup that the parameter is not hashable.

### CODE REVIEW

**Comment by Rad0van** [comment]
Maybe @Yajo or @ernestotejeda could have a look? Thanx.

**Review by yajo — APPROVED** [review]
Code OK

**Review by ernestotejeda — COMMENTED** [review]
Code review: OK

**Review by ernestotejeda — APPROVED** [review]
Functional review: OK

TT25144

**Pull request merged**
