### PR TITLE
[12.0][ADD] new module server_action_sort to sort lines of any models by any criterias

### PR DESCRIPTION
**Pull request by legalsylvain**
Add new module ``server_action_sort``. (similar to ``server_action_navigate`` available [here ](https://github.com/OCA/server-backend/pull/65))
Replace previous module ``mass_sorting`` in server-tools repository for V7 / V8 and [V10](https://github.com/OCA/server-tools/tree/10.0/mass_sorting)

This module allow to configure new server Actions to sort items lines.

For exemple, if you want to sort sale order lines, by any criterias, you can define a new server action like this : 

ir_actions_server_form

A new option, is then available in the action menu :

sale_order_tree

This module provides a generic way to do the same things than other modules like : 

- ``purchase_order_line_deep_sort`` (purchase-workflow [V12](https://github.com/OCA/purchase-workflow/tree/12.0/purchase_order_line_deep_sort)) CC : @cubells, @sergio-teruel 
- ``account_invoice_line_sort`` (account-invoicing) CC : @Cedric-Pigeon

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There are some unrelated commits here. I prefer the name `mass_sorting` :stuck_out_tongue_closed_eyes:

**Comment by legalsylvain** [comment]
> There are some unrelated commits here.

Fixed.

> I prefer the name mass_sorting

Well, the features is the same, but the design has been totally reworked. It is now based on server_action exactly like ``server_action_navigate``. [Ref](https://github.com/OCA/server-ux/pull/129#issuecomment-590908689). I think it's great if all the modules based on the same concept have the same syntax for the technical name. But for the "friendly name", I set "Server Actions - Mass Sort Lines". 
Is it OK for you ?

**Comment by pedrobaeza** [comment]
Yeah, good, I only express my feeling, but the author decides. You can also call it the "sort-enator", hahaha

**Comment by legalsylvain** [comment]
Hi @dreispt, @hbrunn, @flotho could you take a look on that PR (similar to ``server_action_navigate`` that is been merged here https://github.com/OCA/server-backend/pull/65)

It is working on production since 6 monthes without problem.

**Pull request closed without merging**
