### PR TITLE
[14.0][FIX] base_user_role: Access Rights group is not enough to create Roles

### PR DESCRIPTION
**Pull request by Dariosi**
Fixes issue #156 "Access rights" group is not enough to create/edit Roles

### CODE REVIEW

**Review by gaikaz — APPROVED** [review]
💯

**Comment by gaikaz** [comment]
@OCA/server-environment-maintainers 
I suppose you guys are the ones to ping?
Could you please look at this real quick. It's a really simple fix to a tiny bug.
@Dariosi even wrote a test for the bug case.

**Comment by sebalix** [comment]
I think the 15.0 branch has some fixes in that direction (to fix also multi-company issues, like https://github.com/OCA/server-backend/pull/168 ). I would favor a backport of 15.0 fixes to 14.0 instead.

**Comment by sebalix** [comment]
@Dariosi can you test this https://github.com/OCA/server-backend/pull/182 ? It should fix your issue (and others you didn't encountered maybe)

**Comment by Dariosi** [comment]
solved in #182

**Pull request closed without merging**
