### PR TITLE
[15.0][MIG] base_external_dbsource: Migration to version 15.0

### PR DESCRIPTION
**Pull request by carlosdauden**
@Tecnativa TT37273

### CODE REVIEW

**Review by Bilbonet — APPROVED** [review]
LGTM
thanks for the work 👍

**Comment by pedrobaeza** [comment]
@carlosdauden please check tests

**Comment by victoralmau** [comment]
Test error is related to github actions (same error in v14 https://github.com/OCA/server-backend/pull/188). Any idea to solve it?

**Comment by victoralmau** [comment]
Tests fixed.

Pre-commit error will be solved with https://github.com/OCA/server-backend/pull/197

**Pull request merged**
