### PR TITLE
[14.0][FW]base_user_role: Groups-roles navigation

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
@ForgeFlow
This PR is a Forward Port of this IMP: https://github.com/OCA/server-backend/pull/157

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Review by sebalix — COMMENTED** [review]
Can you cherry-pick the same commit done in https://github.com/OCA/server-backend/pull/158/commits ? It is to keep the same message, same timestamp, same author, etc, it helps to back/forward port commits from one branch to another.

A tool is in development to ease this process here: https://github.com/OCA/maintainer-tools/pull/504 (but already quite stable).

**Comment by GuillemCForgeFlow** [comment]
> Can you cherry-pick the same commit done in https://github.com/OCA/server-backend/pull/158/commits ? It is to keep the same message, same timestamp, same author, etc, it helps to back/forward port commits from one branch to another.
> 
> A tool is in development to ease this process here: [OCA/maintainer-tools#504](https://github.com/OCA/maintainer-tools/pull/504) (but already quite stable).

Yes, I did that, but I had to edit the content of the commit as it was not working on v14 with the same content that the commit on v13 had. 
So in that case, would you want me to cherry-pick and then apply the changes on a separate commit?
Also, in relation to that, I opened a fix with a silly change, if you could check it out: https://github.com/OCA/server-backend/pull/161

**Comment by sebalix** [comment]
@GuillemCForgeFlow it's up to you, if the changes are small, you can amend the cherry-picked commit, I often do that to avoid further merge conflicts when porting things to further versions (15.0, 16.0...), but if some changes are big enough, like a refactoring needed, a separate commit is nice.

**Comment by GuillemCForgeFlow** [comment]
Hi @sebalix , I don't know if that would work or not. I don't really know how to cherry-pick the commit: [212621305f80d6b9ae65903cd3e5ada76731c43f ](https://github.com/OCA/server-backend/pull/157/commits/212621305f80d6b9ae65903cd3e5ada76731c43f) and then apply changes on the same commit without losing the timestamp, message, ...
Because if I apply changes I need to perform a fixup on the cherry-picked commit and then I lose the content.
How exactly should I do it?
And thanks in advance! :smile:

**Comment by sebalix** [comment]
@GuillemCForgeFlow as soon as you use `git commit --amend` or a fixup+squash in the original commit it's OK, don't worry about the timestamp, there are two of them in the commit and only the original one (authored one) matters.

**Comment by GuillemCForgeFlow** [comment]
@sebalix Perfect, then now it should be all good! And thanks again for helping :smile:

**Comment by sebalix** [comment]
@GuillemCForgeFlow it is still not good, the message of the commit was `[IMP]base_user_role: Groups-roles navigation`, you renamed it to `[14][FW][IMP]base_user_role: Groups-roles navigation` :) Nothing should change except the content, all other metadata as to stay the same.

**Comment by GuillemCForgeFlow** [comment]
> @GuillemCForgeFlow it is still not good, the message of the commit was `[IMP]base_user_role: Groups-roles navigation`, you renamed it to `[14][FW][IMP]base_user_role: Groups-roles navigation` :) Nothing should change except the content, all other metadata as to stay the same.

Hope now it's okay! :smile:

**Review by sebalix — APPROVED** [review]

**Pull request merged**
