### PR TITLE
[14.0][FIX] base_user_role_company: roles not properly applied on login

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Review by patrickrwilson — APPROVED** [review]
Tested and works great. Thank you.

**Review by rafaelbn — APPROVED** [review]
LGTM 👍

**Review by kos94ok-3D — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Comment by dreispt** [comment]
Tests were failing, fixed them. Will merge once confirm they are passing.

**Pull request merged**
