### PR TITLE
[14.0][MIG] migration of module base_user_role

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

I've migrated the module base_user_role and its functionalities from Odoo 13.0 to 14.0. I've checked if all unit tests are still running.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

This MR contains the change proposed in PR https://github.com/OCA/server-backend/pull/64

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Code review and functional review with runbot

image

It might be necessary to redo the screenshots of the  README.rst  ?

**Comment by hparfr** [comment]
@kevinkhao  Please check if your improvements in v12 need to be included here.

**Comment by sebalix** [comment]
<s>@alan196 can you also cherry-pick this bugfix https://github.com/OCA/server-backend/pull/92 ?</s>
Nevermind, you already fixed the issue.

**Comment by kevinkhao** [comment]
@hparfr Thanks for the ping

@alan196 there was a PR in 12.0 but not 13.0 to add multicompany capability : https://github.com/OCA/server-backend/pull/68/commits/588e8e0daaa206f489ae93679cc3389e586599ed

I will take a look this weekend

**Comment by hparfr** [comment]
ping @kevinkhao

**Comment by kevinkhao** [comment]
LGTM
thanks

**Review by kevinkhao — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Review by CasVissers-360ERP — APPROVED** [review]
Straightforward migration. LGTM

**Comment by StefanRijnhart** [comment]
Can you rebase to fix CI? You need https://github.com/OCA/server-backend/commit/4ad44af4f114665c350800f9f08f78c2acb9e84c

**Comment by StefanRijnhart** [comment]
Thanks!
/ocabot merge nobump

**Comment by StefanRijnhart** [comment]
@alan196 for the record, the description of this PR mentions the inclusion of #64, but it looks like that is not actually the case? Can you confirm?

**Comment by alan196** [comment]
> @alan196 for the record, the description of this PR mentions the inclusion of #64, but it looks like that is not actually the case? Can you confirm?

Thanks for the clarification @StefanRijnhart , the PR #64 was changed from the time I make the PR, I think is better to wait until the PR is merged then make a port to V14. I will be watching the PR.

**Comment by StefanRijnhart** [comment]
Great, thanks!

**Pull request merged**
