### PR TITLE
[17.0] [MIG] base_user_role: Migration to 17.0

### PR DESCRIPTION
**Pull request by rven**

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi. Thanks for porting this module.
could you cherry pick this recent commit : https://github.com/OCA/server-backend/pull/250

thanks !

**Review by legalsylvain — APPROVED** [review]
Diff review. LGTM. 

@sebalix, @jcdrubay, @novawish : could you take a look on this module you are maintaining.

thanks !

**Review by gaikaz — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
