### PR TITLE
11.0 [MIG] base_external_dbsource_mysql

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase now that the dependency has been merged.

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Comment by cubells** [comment]
You must rebase before. But `base_external_dbsource_sqlite` dependecy is not merged.

**Comment by max3903** [comment]
:+1:

**Comment by max3903** [comment]
@pedrobaeza Can you restore the branch and recreate the pull request? `MySQLdb` does not exist as Python Package so I reverted the OCA/11.0 branch.

**Comment by pedrobaeza** [comment]
I don't get it: isn't the CIs green?

**Pull request merged**
