### PR TITLE
[15.0][MIG] base_global_discount

### PR DESCRIPTION
**Pull request by kirca**

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@kirca can you please rebase?

**Comment by kirca** [comment]
Hi @pedrobaeza , I rebased but tests are failing in `base_user_role`

**Comment by pedrobaeza** [comment]
Uhm, so it continues as it was before... Seeing the main branch, it seems green, but I'm not able to relaunch another test to see. @simahawk can you give a hand here?

**Comment by simahawk** [comment]
> Uhm, so it continues as it was before... Seeing the main branch, it seems green, but I'm not able to relaunch another test to see. @simahawk can you give a hand here?

running

**Comment by pedrobaeza** [comment]
@simahawk I don't the see the actions for 15.0 branch. Did you relaunch them? It's to discard a problem in the main branch.

**Comment by simahawk** [comment]
Ah sorry, didn't get it. I re-run them here. I cannot run again successful builds on 15.0 apparently.
I opened a fake PR w/ a dumb modif https://github.com/OCA/server-backend/pull/175

**Comment by pedrobaeza** [comment]
Thanks, I thought it was me not having enough permissions in this repo, but it seems we can't relaunch a success build...

Anyways, now it's clear: the other PR is green, and this one not, so this is something modifying something to make it red.

**Comment by kirca** [comment]
The issue was in the tests for `base_user_role`. There was missing groups in the check which break when product module was installed. I added the fix here.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
