### PR TITLE
[14.0][FIX] base_user_role_profile: Add CRUD Access Right To Profile for ERP Manager

### PR DESCRIPTION
**Pull request by majouda**
This fix is for issue number: #249

### CODE REVIEW

**Comment by majouda** [comment]
Hello @legalsylvain 
Can you please review this PR

@sebalix

**Review by legalsylvain — COMMENTED** [review]
hi. it is not the same for the res_users_role_line model ?

**Comment by majouda** [comment]
> hi. it is not the same for the res_users_role_line model ?

The erp_manager has aleady the CRUD access right to the model res_users_role_line
See following line in "base_user_role" module. 
https://github.com/OCA/server-backend/blob/14.0/base_user_role/security/ir.model.access.csv#L3

Thank you @legalsylvain for the code review

**Review by legalsylvain — APPROVED** [review]
oh. indeed. thanks.

**Comment by abenzbiria** [comment]
Hi @dreispt ,

Could you please take a look on this PR.

Have a nice day

**Comment by TumbaoJu** [comment]
@yvaucher  @sbidoul :  Can you please look at this PR and merge it if everything is ok?

**Review by dreispt — APPROVED** [review]

**Comment by abenzbiria** [comment]
Thanks @dreispt

**Pull request merged**
