### PR TITLE
[12.0][MIG] base_external_dbsource_sqlite

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Depends on:

- [x] base_external_dbsource - #20 

Migration of module base_external_dbsource_sqlite to v12.0

### CODE REVIEW

**Comment by dalonsod** [comment]
@ageficent #20 is already merged, could you resume this?
Anyway, I think `requirements.txt` with `sqlalchemy` dependency is missing. Is that correct?
Thanks!

**Comment by AdriaGForgeFlow** [comment]
> @ageficent #20 is already merged, could you resume this?
> Anyway, I think `requirements.txt` with `sqlalchemy` dependency is missing. Is that correct?
> Thanks!

Done :+1:

**Comment by dalonsod** [comment]
Well, I think `oca_dependencies.txt` is no longer required and should be removed

**Comment by dalonsod** [comment]
> 
> 
> Well, I think `oca_dependencies.txt` is no longer required and should be removed

@ageficent can you review this?

**Review by dalonsod — APPROVED** [review]
Ignoring codecov status, I think it's fine

**Comment by pedrobaeza** [comment]
Sorry, we haven't seen your PR and proceed with the merge of another one, #58 

I hope you don't mind.

**Pull request closed without merging**
