### PR TITLE
[MIG] base_user_role: Migration to 15.0

### PR DESCRIPTION
**Pull request by Tatider**
Also, fix problem with Roles creation by "Administrator/Access Rights"

### CODE REVIEW

**Comment by Tatider** [comment]
Hello @sebalix and @jcdrubay 
Can you, please, check the Merge request, so I can migrate the "base_user_role_company" as well.

**Review by alan196 — APPROVED** [review]

**Review by tbaden — APPROVED** [review]
did a code review: lgtm

**Pull request merged**
