### PR TITLE
[17.0][IMP] base_user_role: Adding alert in user when role is used

### PR DESCRIPTION
**Pull request by CRogos**
cherry pick of https://github.com/OCA/server-backend/pull/273

@dreispt

### CODE REVIEW

**Review by MohamedOsman7 — APPROVED** [review]
LGTM

**Comment by CRogos** [comment]
@rven could you review? Forward migration of a change in v16.

**Comment by CRogos** [comment]
@pedrobaeza could you also review this. This change was made on v16 after it has been migrated to v17, therefore this commit is missing in v17.

**Review by pedrobaeza — APPROVED** [review]
It's the same as v16:

/ocabot merge minor

**Pull request merged**
