### PR TITLE
14.0 [MIG] base_global_discount

### PR DESCRIPTION
**Pull request by iwkse**

### CODE REVIEW

**Comment by iwkse** [comment]
@pedrobaeza I've opened the same as #131 with rebasing, could you merge this one?

thank you again!

**Comment by pedrobaeza** [comment]
There's #131 already

**Comment by iwkse** [comment]
> There's #131 already

yes but it's stuck and it can't be merged at the current state.

**Review by francesco-ooops — CHANGES_REQUESTED** [review]
for some reason on runboat module description appears like this

image

**Comment by iwkse** [comment]
> for some reason on runboat module description appears like this
> 
> image

Indeed, that's also in the #131 and also on 12.0 and 11.0. There's old link pointing at openerp.com and missing images, I can't find a branch where this was showing correctly.
Any hint @pedrobaeza @chienandalu @rafaelbn ?

**Pull request closed without merging**
