### PR TITLE
[12.0][MIG] base_external_dbsource_mysql

### PR DESCRIPTION
**Pull request by pedrobaeza**
Depends on:

- [x] base_external_dbsource - #20 

Supersedes #22 for removing the dependency to base_external_dbsource_sqlite, which it doesn't worth.

@Tecnativa TT23526

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Great. It was clueless to depend on the sqlite module

**Comment by pedrobaeza** [comment]
Let's merge it as it has been around a lot of time (if CIs go right):

/ocabot merge nobump

**Comment by ValentinVinagre** [comment]
Hi @pedrobaeza ,
Shouldn't "MySQLdb" library be added in the requirements.txt file?

**Comment by pedrobaeza** [comment]
Not really, as it's a dependency in the module, but tests are mocked.

**Comment by pedrobaeza** [comment]
I'm going to check anyway to see and correct README.

**Comment by ValentinVinagre** [comment]
> Not really, as it's a dependency in the module, but tests are mocked.

okay, thanks 👍

**Comment by pedrobaeza** [comment]
@ValentinVinagre the requirement is already there:

https://github.com/OCA/server-backend/blob/12.0/requirements.txt#L2

but the explanation about mocked tests is still applicable.

**Comment by ValentinVinagre** [comment]
Hi @pedrobaeza ,
It's true, the 'mysqlclient' library contains the "MySQLdb".
Just one thing, in the Installation of readme the "base_external_dbsource_sqlite" module isn't necessary, right?

**Comment by pedrobaeza** [comment]
It's already removed:

/ocabot merge nobump

**Review by ValentinVinagre — APPROVED** [review]
Nice work 👍

**Pull request merged**
