### PR TITLE
[13.0][MIG] base_user_role_history: Migration to 13.0

### PR DESCRIPTION
**Pull request by baimont**
This PR depends on https://github.com/OCA/server-backend/pull/46
and needs its last commit to be deleted once https://github.com/OCA/server-backend/pull/46
will be merged

### CODE REVIEW

**Comment by baimont** [comment]
@ThomasBinsfeld 
@sebalix

**Review by ThomasBinsfeld — APPROVED** [review]

**Review by njeudy — APPROVED** [review]
Just install it on a test database, and all is ok for me.

**Review by sebalix — APPROVED** [review]
Waiting for #46 to be merged.

**Comment by dreispt** [comment]
There are issues with the Travis linting.

**Review by HaraldPanten — APPROVED** [review]
👍

**Pull request merged**
