### PR TITLE
[12.0][IMP] update repository template

### PR DESCRIPTION
**Pull request by huguesdk**
update repository with https://github.com/OCA/oca-addons-repo-template using copier. one of the goals is to fix the ci that currently fails with travis (like on #226), as explained in OCA/maintainer-quality-tools#712.

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @huguesdk . could you take a look on the red ci ?

**Comment by huguesdk** [comment]
yes, sure, i’m on it.

**Comment by huguesdk** [comment]
it’s green. 🎉

**Review by legalsylvain — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
